### ISSUE TITLE
Recipe collision due to OreDictionary of UniversalBucket for FluidHoney

### ISSUE THREAD

**Issue by VonZeeple** [GrowthcraftCE/Growthcraft-1.12#48] opened 2018-11-11 16:05 UTC
### Expected Behavior
Should be able to craft vanilla milk bucket with one Animania milk bucket.

### Actual Behavior
Obtain 1 honey (from Harvestcraft) instead of one vanilla milk bucket

### Steps to Reproduce
Mod list:
Animania 1.6.0.2
CraftStudio API 1.0.0
GrowthCraft 4.0.4.100
HarvestCraft 1.12a

Problem is solved when disabling either Growthcraft or HarvestCraft.

**Comment by Deshiba** [comment] 2018-11-24 12:14
For clarification. This only happens when Growthcraft is present. When animania is installed next to rustic, harvestcraft or forestry everything behaves as intended.

**Comment by Alatyami** [comment] 2018-12-04 07:32
Trying to figure out how this is a Growthcraft issue. We do not have a recipe for a Honey item or a recipe that uses a Milk bucket. So, I am not seeing how Growthcraft could be affecting a recipe that results in a harvestcraft:honeyitem.  I've checked Pam's source code as well, and they do not have a recipe that takes a bucket and makes the honeyitem.

**Comment by Syndaryl** [comment] 2018-12-04 13:10
There's something funky going on with NBT that I can't figure out. I've had some pretty wacky results adding milk related conversions via CraftTweaker, and I've not had this trouble with NBT bucket recipes before.

**Comment by Deshiba** [comment] 2018-12-04 13:37
I can't reproduce this with just Animania and Growthcraft
![milk](https://user-images.githubusercontent.com/10565800/49445050-3a1ced80-f7d1-11e8-8844-8ed41fccccab.jpg)

I'm using forge 14.23.5.4768, mod versions below:
![multi mc](https://user-images.githubusercontent.com/10565800/49445137-75b7b780-f7d1-11e8-9879-e75b59c28565.jpg)

So this doesn't seem to be an issue for Animania and GrowthcraftCE on their own...

**Comment by Alatyami** [comment] 2018-12-04 13:39
I check Pam's code as well and nothing stuck out. Their recipe for honey doesn't use milk.

This is very odd behavior.

**Comment by Deshiba** [comment] 2018-12-04 13:57
Did some cross mod testing. I can dispel that this is something caused by NBT on the items themselves. In all configurations the NBT is identical:
![nbtexplorer results](https://user-images.githubusercontent.com/10565800/49446633-ef04d980-f7d4-11e8-9057-77ad40f3ffee.jpg)

**Comment by renadi** [comment] 2018-12-04 14:04
Does Pam's have a recipe for a bucket of honey to its honey item?

It could be the bucket itself that's the issue.

**Comment by Deshiba** [comment] 2018-12-04 14:14
@renadi No, a bucket of milk turns into 4 "fresh milk". It's definitely some weirdness with conversions though:
* With just Harvestcraft; 
** Bucket of milk (vanilla)-> Fresh milk (harvestcraft)
* With just Animania:
** Bucket of milk (animania) -> Bucket of milk (vanilla)

* With Animania and Growthcraft:  
** Bucket of milk (animania) -> Bucket of milk (vanilla)
*With Animania and Harvestcraft:
** Bucket of milk (animania) -> Bucket of milk (vanilla)
** Bucket of milk (vanilla)-> Fresh milk (harvestcraft)
* With Growthcraft and Harvestcraft; 
** Bucket of milk (vanilla)-> Fresh milk (harvestcraft)

* With Animania, Growthcraft and Harvestcraft: 
** Bucket of milk (animania) -> Honey (harvestcraft)
** Bucket of milk (vanilla) -> Fresh milk (harvestcraft)

**Comment by Alatyami** [comment] 2018-12-04 14:35
I also added CraftTweaker and Minetweaker to show the recipe source and they didn't pickup any registered recipe. Really odd.

**Comment by Deshiba** [comment] 2018-12-04 14:53
On another note, this also happens with Slop:
![2018-12-04_15 52 39](https://user-images.githubusercontent.com/10565800/49450191-cd0f5500-f7dc-11e8-8f36-1a5286487ec1.png)

**Comment by Deshiba** [comment] 2018-12-04 15:19
Turns out the same thing happens when GrowthcraftCE, Harvestcraft and Thermal Foundation are in a mod together. Naphta converts to honey:
![naphta](https://user-images.githubusercontent.com/10565800/49451578-c504e480-f7df-11e8-90ad-f803c67706f7.jpg)

When consulting an Animania dev about the issue he pointed out that you can't add universal buckets to the OreDictionary without getting issues. Skimming trough the files he landed on the following lines:
https://github.com/GrowthcraftCE/Growthcraft-1.11/blob/5c199f191cbc02cae8e1561c84be321904c9a13d/src/main/java/growthcraft/bees/init/GrowthcraftBeesFluids.java#L34-L35

I coulnd't quickly find the same thing on 1.12 because the structure is different.

**Comment by Alatyami** [comment] 2018-12-04 15:51
https://github.com/GrowthcraftCE/Growthcraft-1.12/blob/1230c650844a015aaf6095843c5f28f3a7c92ee2/src/main/java/growthcraft/bees/common/Init.java

```
	public static void registerFluidOres() {
		if (GrowthcraftBeesFluids.honey != null)
		{
			OreDictionary.registerOre("bottleHoney", GrowthcraftBeesFluids.honey.asBottleItemStack());
//			OreDictionary.registerOre("bucketHoney", honey.asBucketItemStack());
			OreDictionary.registerOre("honeyDrop", GrowthcraftBeesFluids.honey.asBucketItemStack());
			OreDictionary.registerOre("dropHoney", GrowthcraftBeesFluids.honey.asBucketItemStack());
		}
}
```

Later today, I'll work with it. Seems odd though that this would only affect Animania Buckets recipes and no other mod has the same affect.

**Comment by Deshiba** [comment] 2018-12-04 16:14
As discussed over discord. The same thing happens with CoFH thermal Foundation (and it's dependancies) when installed along Harvestcraft and GrowthcraftCE.
![2018-12-04_17 07 46](https://user-images.githubusercontent.com/10565800/49455696-e073ed80-f7e7-11e8-88cb-1bf9dffe7c3a.png)
![modlist](https://user-images.githubusercontent.com/10565800/49455764-fda8bc00-f7e7-11e8-982b-1f4af7d0260a.jpg)

**Comment by SirChamomile** [comment] 2018-12-04 17:05
Yeah Biodeisel from Immersive Engineering does the same thing.

**Closed** 2018-12-05 20:37 UTC
Labels: bug
