### ISSUE TITLE
Radiation Crash?

### ISSUE THREAD

**Issue by EightBlade** [GrowthcraftCE/Growthcraft-1.12#180] opened 2019-05-08 08:21 UTC
https://pastebin.com/btmfk9j9

**Comment by mindforger** [comment] 2019-05-08 08:27
https://github.com/GrowthcraftCE/Growthcraft-1.12/issues/166 related

**Comment by Alatyami** [comment] 2019-05-11 15:27
Closing as duplicate of #166 this will be resolved in the next snapshot release.

**Closed by Alatyami** 2019-05-11 15:27 UTC
